### ISSUE TITLE
how to install? could it support redmine 3.3?

### ISSUE THREAD

**Issue by archonwang** [nmikhno/redmine_estimates#1]
@nmikhno , 
how to install? could it support redmine 3.3?

Thanks.

**Comment by nmikhno** [comment]
Hi, @archonwang 

Actually,  the plugin is under development now, this is a draft copy. The working version of redmine is 2.6.1 

As soon  as I finish with the current version I could provide compatibility for 3.3 if you still going to need this.

**Comment by archonwang** [comment]
@nmikhno ， Thanks for your reply. if it has been release, please inform me to test it. Thanks.

**Comment by archonwang** [comment]
OK, I will test it on Redmine 3.3.X these days. if there's any question I will report it ASAP

Thanks.

**Comment by nmikhno** [comment]
Hi, @archonwang! 
Check out a new [branch](https://github.com/nmikhno/redmine_estimates/tree/3.x.x) for 3.x.x Redmine version
Today I've fixed some compatibility bugs and add minor improvements. 
I've tested it on  Redmine 3.3.0.stable
